### ISSUE TITLE
Can't find the table

### ISSUE THREAD

**Issue by AaronZhu2018** [mkhuthir/RoboND-Perception-Project#1]
After I run this code ./pr2_safe_spawner.sh
I just can see the pr2 robot both in gazebo and rviz, but i cannot see the table and item 
![image](https://user-images.githubusercontent.com/25722824/50406859-57a90a00-0807-11e9-8585-38855df8491a.png)
![image](https://user-images.githubusercontent.com/25722824/50406862-67c0e980-0807-11e9-9b31-298be3f7b1c8.png)
![image](https://user-images.githubusercontent.com/25722824/50406865-70192480-0807-11e9-8e50-895d44c3ccc6.png)
please help! thank you in advance

**Comment by mkhuthir** [comment]
Hello

Your screen shot showing that node pr2_robot is not found. please check your launch files and adjust the settings:

select the required test world by changing the following lines in pick_place_project.launch

    
    <arg name="world_name" value="$(find pr2_robot)/worlds/test1.world"/>
and

    
    <rosparam command="load" file="$(find pr2_robot)/config/pick_list_1.yaml"/>
Results are as following:

**Comment by AaronZhu2018** [comment]
Thank you for your reply. Really appreciate!
I didn't change anything in your code. I just git clone it to my catkin_ws and then I follow this guide
![image](https://user-images.githubusercontent.com/25722824/50425516-2128c900-08b3-11e9-9bbd-8990494699de.png)
From here https://github.com/georgeerol/RoboticPerception?fbclid=IwAR1K2KOrT9H8Scdi-g6xDMQjRhfyBN1zWYzwg160dfOlgSBAVSGzKj9SHVM

But I fail, as I mention I only see the pr2_robot. Can you give me more details on how to run your project. Please really need help.
